version: '2'
services:
    jenkins-app:
        image: jenkins
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jenkins-mysql:3306/jenkins?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jenkins-mysql:
        extends:
            file: mysql.yml
            service: jenkins-mysql
